# Generated by Django 4.0.1 on 2022-01-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=200)),
                ('p1name', models.CharField(max_length=200)),
                ('p1email', models.CharField(max_length=200)),
                ('p2name', models.CharField(max_length=200)),
                ('p2email', models.CharField(max_length=200)),
                ('p3name', models.CharField(max_length=200)),
                ('p3email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Troops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldiers', models.IntegerField(default=0)),
                ('tanks', models.IntegerField(default=0)),
                ('bombers', models.IntegerField(default=0)),
                ('aag', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagpoints', models.IntegerField(default=0)),
                ('battlepoints', models.IntegerField(default=0)),
                ('defensepoints', models.IntegerField(default=0)),
                ('attackpoints', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shield', models.DateTimeField()),
                ('attack', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
