# Generated by Django 4.0.1 on 2022-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooldown',
            name='attack',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cooldown',
            name='shield',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
