# Generated by Django 4.0.1 on 2022-01-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_powerup'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerup',
            name='shield',
            field=models.IntegerField(default=0),
        ),
    ]
