# Generated by Django 4.0.1 on 2022-01-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_powerup_shield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerup',
            name='shield',
        ),
    ]
