# Generated by Django 4.0.1 on 2022-01-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_powerup_shield'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyFp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent', models.DateTimeField(blank=True, null=True)),
                ('poisoned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
