# Generated by Django 4.0.1 on 2022-01-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_hourlyfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyfp',
            name='bonusfp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hourlyfp',
            name='bonustill',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyfp',
            name='poisonedtill',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
