# Generated by Django 4.0.1 on 2022-01-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='recentupdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
